import enum


class Kayttajatyyppi(enum.Enum):
    ADMIN = "ADMIN"
    OPH_STAFF = "OPH_STAFF"
    VIRKAILIJA = "VIRKAILIJA"
    PAAKAYTTAJA = "PAAKAYTTAJA"
    PALVELU = "PALVELU"
    OPPIJA_CAS = "OPPIJA_CAS"
    OPPIJA_CAS_VALTUUDET = "OPPIJA_CAS_VALTUUDET"
