# Generated by Django 2.1.1 on 2019-01-31 15:50

from django.db import migrations, models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z3_additionalcasuserfields',
            name='henkilo_oid',
            field=models.CharField(blank=True, max_length=50, validators=[varda.validators.validate_henkilo_oid]),
        ),
    ]
