# Generated by Django 2.1.1 on 2019-02-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0002_auto_20190131_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='henkilo',
            name='aidinkieli_koodi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='henkilo',
            name='postinumero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='henkilo',
            name='sukupuoli_koodi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalhenkilo',
            name='aidinkieli_koodi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalhenkilo',
            name='postinumero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalhenkilo',
            name='sukupuoli_koodi',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
