# Generated by Django 2.1.7 on 2019-05-15 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varda', '0003_auto_20190201_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHuoltajuussuhde',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('voimassa_kytkin', models.BooleanField(default=True)),
                ('luonti_pvm', models.DateTimeField(blank=True, editable=False)),
                ('muutos_pvm', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical huoltajuussuhde',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Huoltajuussuhde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voimassa_kytkin', models.BooleanField(default=True)),
                ('luonti_pvm', models.DateTimeField(auto_now_add=True)),
                ('muutos_pvm', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huoltajuussuhteet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'huoltajuussuhteet',
            },
        ),
        migrations.RemoveField(
            model_name='historicalhuoltaja',
            name='alkamis_pvm',
        ),
        migrations.RemoveField(
            model_name='historicalhuoltaja',
            name='paattymis_pvm',
        ),
        migrations.RemoveField(
            model_name='huoltaja',
            name='alkamis_pvm',
        ),
        migrations.RemoveField(
            model_name='huoltaja',
            name='lapset',
        ),
        migrations.RemoveField(
            model_name='huoltaja',
            name='paattymis_pvm',
        ),
        migrations.AlterField(
            model_name='huoltaja',
            name='henkilo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='huoltaja', to='varda.Henkilo'),
        ),
        migrations.AddField(
            model_name='huoltajuussuhde',
            name='huoltaja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huoltajuussuhteet', to='varda.Huoltaja'),
        ),
        migrations.AddField(
            model_name='huoltajuussuhde',
            name='lapsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huoltajuussuhteet', to='varda.Lapsi'),
        ),
        migrations.AddField(
            model_name='huoltajuussuhde',
            name='maksupaatokset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maksupaatokset', to='varda.Maksupaatos'),
        ),
        migrations.AddField(
            model_name='historicalhuoltajuussuhde',
            name='huoltaja',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.Huoltaja'),
        ),
        migrations.AddField(
            model_name='historicalhuoltajuussuhde',
            name='lapsi',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.Lapsi'),
        ),
        migrations.AddField(
            model_name='historicalhuoltajuussuhde',
            name='maksupaatokset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.Maksupaatos'),
        ),
    ]
