# Generated by Django 2.2.2 on 2019-06-20 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0006_auto_20190611_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('log_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('log_seq', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'log data',
            },
        ),
        migrations.AlterModelOptions(
            name='aikaleima',
            options={'verbose_name_plural': 'aikaleimat'},
        ),
        migrations.AlterField(
            model_name='aikaleima',
            name='avain',
            field=models.TextField(choices=[('ORGANISAATIOS_LAST_UPDATE', 'ORGANISAATIOS_LAST_UPDATE'), ('HUOLTAJASUHDEMUUTOS_LAST_UPDATE', 'HUOLTAJASUHDEMUUTOS_LAST_UPDATE'), ('AUDIT_LOG_AWS_LAST_UPDATE', 'AUDIT_LOG_AWS_LAST_UPDATE')], unique=True),
        ),
        migrations.AlterField(
            model_name='historicalvarhaiskasvatuspaatos',
            name='tuntimaara_viikossa',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(120.0)]),
        ),
        migrations.AlterField(
            model_name='varhaiskasvatuspaatos',
            name='tuntimaara_viikossa',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(120.0)]),
        ),
    ]
