# Generated by Django 2.2.2 on 2019-07-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0007_auto_20190620_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huoltajuussuhde',
            name='maksutiedot',
            field=models.ManyToManyField(blank=True, related_name='huoltajuussuhteet', to='varda.Maksutieto'),
        ),
    ]
