# Generated by Django 2.2.2 on 2019-07-08 11:12

from django.db import migrations, models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0008_auto_20190704_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='z3_additionalcasuserfields',
            name='huoltaja_oid',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[varda.validators.validate_henkilo_oid]),
        ),
    ]
