# Generated by Django 2.2.6 on 2019-10-31 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varda', '0011_auto_20190904_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvakajarjestaja',
            name='yritysmuoto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vakajarjestaja',
            name='yritysmuoto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='PaosToiminta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voimassa_kytkin', models.BooleanField(default=False)),
                ('luonti_pvm', models.DateTimeField(auto_now_add=True)),
                ('muutos_pvm', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paos_toiminnat', to=settings.AUTH_USER_MODEL)),
                ('oma_organisaatio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paos_jarjestaja', to='varda.VakaJarjestaja')),
                ('paos_organisaatio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paos_toimija', to='varda.VakaJarjestaja')),
                ('paos_toimipaikka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paos_toimija', to='varda.Toimipaikka')),
            ],
            options={
                'verbose_name_plural': 'Paos-toiminnat',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaosToiminta',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('voimassa_kytkin', models.BooleanField(default=False)),
                ('luonti_pvm', models.DateTimeField(blank=True, editable=False)),
                ('muutos_pvm', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oma_organisaatio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.VakaJarjestaja')),
                ('paos_organisaatio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.VakaJarjestaja')),
                ('paos_toimipaikka', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.Toimipaikka')),
            ],
            options={
                'verbose_name': 'historical paos toiminta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='paostoiminta',
            constraint=models.UniqueConstraint(fields=('oma_organisaatio', 'paos_organisaatio'), name='oma_organisaatio_paos_organisaatio_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='paostoiminta',
            constraint=models.UniqueConstraint(fields=('oma_organisaatio', 'paos_toimipaikka'), name='oma_organisaatio_paos_toimipaikka_unique_constraint'),
        ),
    ]
