# Generated by Django 2.2.6 on 2019-11-27 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0013_auto_20191121_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapsi',
            name='oma_organisaatio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paos_lapsi_oma_organisaatio', to='varda.VakaJarjestaja'),
        ),
        migrations.AlterField(
            model_name='lapsi',
            name='paos_organisaatio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paos_lapsi_paos_organisaatio', to='varda.VakaJarjestaja'),
        ),
    ]
