# Generated by Django 2.2.10 on 2020-03-05 08:19

from django.db import migrations, models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0015_auto_20200305_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltoimipaikka',
            name='sahkopostiosoite',
            field=models.CharField(max_length=200, validators=[varda.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='historicalvakajarjestaja',
            name='sahkopostiosoite',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[varda.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='toimipaikka',
            name='sahkopostiosoite',
            field=models.CharField(max_length=200, validators=[varda.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='vakajarjestaja',
            name='sahkopostiosoite',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[varda.validators.validate_email]),
        ),
    ]
