# Generated by Django 2.2.9 on 2020-04-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0017_aikaleima_aikaleima_avain'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallapsi',
            name='vakatoimija',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.VakaJarjestaja'),
        ),
        migrations.AddField(
            model_name='lapsi',
            name='vakatoimija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lapsi_vakatoimija', to='varda.VakaJarjestaja'),
        ),
    ]
