# Generated by Django 2.2.13 on 2020-07-02 13:25

from django.db import migrations, models
import varda.models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0025_auto_20200702_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpidempipoissaolo',
            name='paattymis_pvm',
            field=models.DateField(default=varda.models.paattymis_pvm_default),
        ),
        migrations.AlterField(
            model_name='pidempipoissaolo',
            name='paattymis_pvm',
            field=models.DateField(default=varda.models.paattymis_pvm_default),
        ),
    ]
