# Generated by Django 2.2.12 on 2020-07-08 08:00

from django.db import migrations, models
import django.contrib.postgres.fields
import varda.enums.hallinnointijarjestelma

sql = "ALTER TABLE varda_vakajarjestaja ALTER COLUMN integraatio_organisaatio SET DATA TYPE VARCHAR(50) ARRAY USING CASE WHEN integraatio_organisaatio IS TRUE THEN ARRAY['vakatiedot'] ELSE '{}' END"
reverse_sql = "ALTER TABLE varda_vakajarjestaja ALTER COLUMN integraatio_organisaatio SET DATA TYPE BOOLEAN USING CASE WHEN integraatio_organisaatio @> ARRAY['vakatiedot']::varchar[] THEN TRUE ELSE FALSE END"
sql_history = "ALTER TABLE varda_historicalvakajarjestaja ALTER COLUMN integraatio_organisaatio SET DATA TYPE VARCHAR(50) ARRAY USING CASE WHEN integraatio_organisaatio IS TRUE THEN ARRAY['vakatiedot'] ELSE '{}' END"
reverse_sql_history = "ALTER TABLE varda_historicalvakajarjestaja ALTER COLUMN integraatio_organisaatio SET DATA TYPE BOOLEAN USING CASE WHEN integraatio_organisaatio @> ARRAY['vakatiedot']::varchar[] THEN TRUE ELSE FALSE END"


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0026_auto_20200702_1325'),
    ]

    operations = [
        migrations.RunSQL(
            sql=sql_history,
            reverse_sql=reverse_sql_history,
            state_operations=[
                migrations.AlterField(
                    model_name='historicalvakajarjestaja',
                    name='integraatio_organisaatio',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
                ),
            ]
        ),
        migrations.RunSQL(
            sql=sql,
            reverse_sql=reverse_sql,
            state_operations=[
                migrations.AlterField(
                    model_name='vakajarjestaja',
                    name='integraatio_organisaatio',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
                ),
            ]
        ),
        migrations.RenameField(
            model_name='historicaltoimipaikka',
            old_name='lahdejarjestelma',
            new_name='hallinnointijarjestelma',
        ),
        migrations.AlterField(
            model_name='historicaltoimipaikka',
            name='hallinnointijarjestelma',
            field=models.CharField(choices=[('VARDA', 'VARDA'), ('ORGANISAATIO', 'ORGANISAATIOPALVELU')], default=varda.enums.hallinnointijarjestelma.Hallinnointijarjestelma('VARDA'), max_length=50),
        ),
        migrations.RenameField(
            model_name='toimipaikka',
            old_name='lahdejarjestelma',
            new_name='hallinnointijarjestelma',
        ),
        migrations.AlterField(
            model_name='toimipaikka',
            name='hallinnointijarjestelma',
            field=models.CharField(choices=[('VARDA', 'VARDA'), ('ORGANISAATIO', 'ORGANISAATIOPALVELU')], default=varda.enums.hallinnointijarjestelma.Hallinnointijarjestelma('VARDA'), max_length=50),
        ),
    ]
