# Generated by Django 2.2.13 on 2020-08-03 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0027_auto_20200708_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaksutieto',
            name='palveluseteli_arvo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='maksutieto',
            name='palveluseteli_arvo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
