# Generated by Django 2.2.13 on 2020-09-14 12:46

import django.core.validators
from django.db import migrations, models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0030_auto_20200907_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaydennyskoulutus',
            name='koulutuspaivia',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[varda.validators.create_validate_decimal_steps('0.5'), django.core.validators.MaxValueValidator(160)]),
        ),
        migrations.AlterField(
            model_name='taydennyskoulutus',
            name='koulutuspaivia',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[varda.validators.create_validate_decimal_steps('0.5'), django.core.validators.MaxValueValidator(160)]),
        ),
    ]
