# Generated by Django 2.2.13 on 2020-09-17 11:22

from django.db import migrations, models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0031_auto_20200914_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='henkilo',
            name='henkilo_oid',
            field=models.CharField(max_length=50, validators=[varda.validators.validate_henkilo_oid]),
        ),
        migrations.AlterField(
            model_name='historicalhenkilo',
            name='henkilo_oid',
            field=models.CharField(max_length=50, validators=[varda.validators.validate_henkilo_oid]),
        ),
    ]
