# Generated by Django 2.2.13 on 2020-10-14 13:27

from django.db import migrations, models
import varda.models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0032_auto_20200917_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpidempipoissaolo',
            name='paattymis_pvm',
            field=models.DateField(default=varda.models.paattymis_pvm_default, validators=[varda.validators.validate_pidempi_poissaolo_paattymis_pvm]),
        ),
        migrations.AlterField(
            model_name='pidempipoissaolo',
            name='paattymis_pvm',
            field=models.DateField(default=varda.models.paattymis_pvm_default, validators=[varda.validators.validate_pidempi_poissaolo_paattymis_pvm]),
        ),
    ]
