# Generated by Django 2.2.13 on 2020-11-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0034_auto_20201029_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvarhaiskasvatuspaatos',
            name='tilapainen_vaka_kytkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='varhaiskasvatuspaatos',
            name='tilapainen_vaka_kytkin',
            field=models.BooleanField(default=False),
        ),
    ]
