# Generated by Django 3.1.4 on 2020-12-22 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0038_auto_20201201_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpalvelussuhde',
            name='tyoaika_viikossa',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='palvelussuhde',
            name='tyoaika_viikossa',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
    ]
