# Generated by Django 3.1.4 on 2021-01-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0039_auto_20201222_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvakajarjestaja',
            name='tilinumero',
        ),
        migrations.RemoveField(
            model_name='vakajarjestaja',
            name='tilinumero',
        ),
    ]
