# Generated by Django 3.1.4 on 2021-01-27 10:20

import django.contrib.postgres.fields
from django.db import migrations, models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0040_auto_20210121_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='z3_additionalcasuserfields',
            name='huoltaja_oid',
        ),
        migrations.AddField(
            model_name='z3_additionalcasuserfields',
            name='etunimet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='z3_additionalcasuserfields',
            name='huollettava_oid_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, validators=[varda.validators.validate_henkilo_oid]), null=True, size=None, validators=[varda.validators.validate_arrayfield]),
        ),
        migrations.AddField(
            model_name='z3_additionalcasuserfields',
            name='kutsumanimi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='z3_additionalcasuserfields',
            name='sukunimi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='z3_additionalcasuserfields',
            name='henkilo_oid',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[varda.validators.validate_henkilo_oid]),
        ),
    ]
