# Generated by Django 3.1.4 on 2021-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0041_auto_20210127_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltilapainenhenkilosto',
            name='tuntimaara',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tilapainenhenkilosto',
            name='tuntimaara',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
