# Generated by Django 3.1.4 on 2021-03-18 07:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varda', '0044_auto_20210225_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z4_caskayttooikeudet',
            name='kayttooikeus',
            field=models.CharField(blank=True, choices=[('VARDA-PAAKAYTTAJA', 'Varda-Pääkäyttäjä'), ('VARDA-TALLENTAJA', 'Varda-Tallentaja'), ('VARDA-KATSELIJA', 'Varda-Katselija'), ('VARDA-PALVELUKAYTTAJA', 'Varda-Palvelukäyttäjä'), ('HUOLTAJATIETO_TALLENNUS', 'Varda-Huoltajatietojen tallentaja'), ('HUOLTAJATIETO_KATSELU', 'Varda-Huoltajatietojen katselija'), ('HENKILOSTO_TAYDENNYSKOULUTUS_KATSELIJA', 'Varda-Täydennyskoulutustietojen katselija'), ('HENKILOSTO_TAYDENNYSKOULUTUS_TALLENTAJA', 'Varda-Täydennyskoulutustietojen tallentaja'), ('HENKILOSTO_TILAPAISET_KATSELIJA', 'Varda-Tilapäisen henkilöstön katselija'), ('HENKILOSTO_TILAPAISET_TALLENTAJA', 'Varda-Tilapäisen henkilöstön tallentaja'), ('HENKILOSTO_TYONTEKIJA_KATSELIJA', 'Varda-Työntekijätietojen katselija'), ('HENKILOSTO_TYONTEKIJA_TALLENTAJA', 'Varda-Työntekijätietojen tallentaja'), ('VARDA_TOIMIJATIEDOT_KATSELIJA', 'Varda-Toimijatietojen katselija'), ('VARDA_TOIMIJATIEDOT_TALLENTAJA', 'Varda-Toimijatietojen tallentaja'), ('VARDA_RAPORTTIEN_KATSELIJA', 'Varda-Raporttien katselija'), ('VARDA_LUOVUTUSPALVELU', 'VARDA_LUOVUTUSPALVELU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='z6_requestlog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.CreateModel(
            name='Z8_ExcelReportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('target_date', models.DateField(null=True)),
                ('started_timestamp', models.DateTimeField()),
                ('finished_timestamp', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('file_size', models.IntegerField()),
                ('number_of_rows', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, validators=[varda.validators.validate_arrayfield])),
                ('toimipaikka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excel_report_logs', to='varda.toimipaikka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_report_logs', to=settings.AUTH_USER_MODEL)),
                ('vakajarjestaja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_report_logs', to='varda.vakajarjestaja')),
            ],
            options={
                'verbose_name_plural': 'Excel report logs',
            },
        ),
        migrations.CreateModel(
            name='Z8_ExcelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('s3_object_path', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
                ('report_type', models.CharField(max_length=50)),
                ('target_date', models.DateField(null=True)),
                ('language', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('toimipaikka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excel_reports', to='varda.toimipaikka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_reports', to=settings.AUTH_USER_MODEL)),
                ('vakajarjestaja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_reports', to='varda.vakajarjestaja')),
            ],
            options={
                'verbose_name_plural': 'Excel reports',
            },
        ),
        migrations.CreateModel(
            name='LoginCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=50)),
                ('api_path', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logincertificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Login certificates',
            },
        ),
    ]
