# Generated by Django 3.1.4 on 2021-08-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0050_auto_20210826_0923'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tutkinto',
            constraint=models.UniqueConstraint(fields=('henkilo', 'vakajarjestaja', 'tutkinto_koodi'), name='unique_tutkinto'),
        ),
    ]
