# Generated by Django 3.1.4 on 2021-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0051_auto_20210831_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='z2_code',
            name='alkamis_pvm',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AddField(
            model_name='z2_code',
            name='paattymis_pvm',
            field=models.DateField(null=True),
        ),
    ]
