# Generated by Django 3.1.4 on 2021-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0052_auto_20210906_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='z8_excelreport',
            name='target_date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='z8_excelreport',
            name='target_date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='z8_excelreportlog',
            name='target_date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='z8_excelreportlog',
            name='target_date_start',
            field=models.DateField(null=True),
        ),
    ]
