# Generated by Django 3.2.7 on 2021-10-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0055_z8_excelreportlog_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='z5_auditlog',
            name='query_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='z5_auditlog',
            name='successful_get_request_path',
            field=models.CharField(max_length=200),
        ),
    ]
