# Generated by Django 3.2.10 on 2021-12-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0057_z6_requestlog_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z9_RelatedObjectChanged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('instance_id', models.IntegerField()),
                ('parent_model_name', models.CharField(max_length=200, null=True)),
                ('parent_instance_id', models.IntegerField(null=True)),
                ('trigger_model_name', models.CharField(max_length=200)),
                ('trigger_instance_id', models.IntegerField()),
                ('changed_timestamp', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Related object changed',
            },
        ),
        migrations.AddIndex(
            model_name='z9_relatedobjectchanged',
            index=models.Index(fields=['model_name', 'changed_timestamp'], name='varda_z9_re_model_n_deef3a_idx'),
        ),
        migrations.AddIndex(
            model_name='z9_relatedobjectchanged',
            index=models.Index(fields=['model_name', 'parent_instance_id', 'changed_timestamp'], name='varda_z9_re_model_n_1f2d14_idx'),
        ),
        migrations.AddIndex(
            model_name='z9_relatedobjectchanged',
            index=models.Index(fields=['model_name', 'instance_id', 'trigger_model_name', 'changed_timestamp'], name='varda_z9_re_model_n_5aeef1_idx'),
        ),
    ]
