# Generated by Django 4.0.1 on 2022-02-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0060_yritysmuoto'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='z9_relatedobjectchanged',
            index=models.Index(fields=['parent_model_name', 'parent_instance_id', 'changed_timestamp'], name='varda_z9_re_parent__34baf3_idx'),
        ),
    ]
