# Generated by Django 4.0 on 2022-02-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0062_alter_z2_codetranslation_description_and_more'),
    ]

    operations = [
        migrations.RunSQL(sql='create index varda_historicallapsi_id_idx on varda_historicallapsi (id);',
                          reverse_sql='drop index varda_historicallapsi_id_idx;'),
        migrations.RunSQL(sql='create index varda_historicalhuoltajuussuhde_id_idx on varda_historicalhuoltajuussuhde (id);',
                          reverse_sql='drop index varda_historicalhuoltajuussuhde_id_idx;'),
        migrations.RunSQL(sql='create index varda_historicalmaksutieto_id_idx on varda_historicalmaksutieto (id);',
                          reverse_sql='drop index varda_historicalmaksutieto_id_idx;'),
        migrations.RunSQL(sql='create index varda_historicalvarhaiskasvatuspaatos_id_idx on varda_historicalvarhaiskasvatuspaatos (id);',
                          reverse_sql='drop index varda_historicalvarhaiskasvatuspaatos_id_idx;'),
        migrations.RunSQL(sql='create index varda_historicalvarhaiskasvatussuhde_id_idx on varda_historicalvarhaiskasvatussuhde (id);',
                          reverse_sql='drop index varda_historicalvarhaiskasvatussuhde_id_idx;'),
    ]
