# Generated by Django 4.0.1 on 2022-03-09 08:06

import django.contrib.postgres.fields
from django.db import migrations, models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0063_add_historical_vakatieto_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z3_additionalcasuserfields',
            name='huollettava_oid_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, validators=[varda.validators.validate_henkilo_oid]), blank=True, null=True, size=None, validators=[varda.validators.validate_arrayfield]),
        ),
        migrations.AlterField(
            model_name='z7_additionaluserfields',
            name='password_changed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
