# Generated by Django 4.0.1 on 2022-03-28 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0066_organisaatio'),
    ]

    operations = [
        # Set default=1 so that this migration is reversible
        migrations.AlterField(
            model_name='henkilo',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='henkilot', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='henkilo',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalhenkilo',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalhuoltaja',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalhuoltajuussuhde',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalkielipainotus',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicallapsi',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalmaksutieto',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalmaksutietohuoltajuussuhde',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalorganisaatio',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalpalvelussuhde',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalpaosoikeus',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalpaostoiminta',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalpidempipoissaolo',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltaydennyskoulutus',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltaydennyskoulutustyontekija',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltilapainenhenkilosto',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltoiminnallinenpainotus',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltoimipaikka',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltutkinto',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltyontekija',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltyoskentelypaikka',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalvarhaiskasvatuspaatos',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalvarhaiskasvatussuhde',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalyearlyreportsummary',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='huoltaja',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huoltajat', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='huoltaja',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='huoltajuussuhde',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huoltajuussuhteet', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='huoltajuussuhde',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='kielipainotus',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kielipainotukset', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='kielipainotus',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='lapsi',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lapset', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='lapsi',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='maksutieto',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maksutiedot', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='maksutieto',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='maksutietohuoltajuussuhde',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maksutiedot_huoltajuussuhteet', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='maksutietohuoltajuussuhde',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='organisaatio',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisaatiot', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='organisaatio',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='palvelussuhde',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palvelussuhteet', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='palvelussuhde',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='paosoikeus',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paos_oikeudet', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='paosoikeus',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='paostoiminta',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paos_toiminnat', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='paostoiminta',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='pidempipoissaolo',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pidemmatpoissaolot', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='pidempipoissaolo',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='taydennyskoulutus',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taydennyskoulutukset', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='taydennyskoulutus',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='taydennyskoulutustyontekija',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taydennyskoulutukset_tyontekijat', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='taydennyskoulutustyontekija',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='tilapainenhenkilosto',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tilapainen_henkilosto', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='tilapainenhenkilosto',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='toiminnallinenpainotus',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toiminnallisetpainotukset', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='toiminnallinenpainotus',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='toimipaikka',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toimipaikat', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='toimipaikka',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='tutkinto',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutkinnot', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='tutkinto',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='tyontekija',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyontekijat', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='tyontekija',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='tyoskentelypaikka',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyoskentelypaikat', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='tyoskentelypaikka',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='varhaiskasvatuspaatos',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varhaiskasvatuspaatokset', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='varhaiskasvatuspaatos',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='varhaiskasvatussuhde',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varhaiskasvatussuhteet', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='varhaiskasvatussuhde',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='yearlyreportsummary',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yearlyreportsummary', to=settings.AUTH_USER_MODEL, default=1)
        ),
        migrations.RemoveField(
            model_name='yearlyreportsummary',
            name='changed_by',
        ),
    ]
