# Generated by Django 4.0.5 on 2022-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0068_remove_z9_relatedobjectchanged_varda_z9_re_model_n_deef3a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalhenkilo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical henkilo', 'verbose_name_plural': 'historical henkilöt'},
        ),
        migrations.AlterModelOptions(
            name='historicalhuoltaja',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical huoltaja', 'verbose_name_plural': 'historical huoltajat'},
        ),
        migrations.AlterModelOptions(
            name='historicalhuoltajuussuhde',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical huoltajuussuhde', 'verbose_name_plural': 'historical huoltajuussuhteet'},
        ),
        migrations.AlterModelOptions(
            name='historicalkielipainotus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical kieli painotus', 'verbose_name_plural': 'historical kielipainotukset'},
        ),
        migrations.AlterModelOptions(
            name='historicallapsi',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical lapsi', 'verbose_name_plural': 'historical lapset'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaksutieto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical maksutieto', 'verbose_name_plural': 'historical maksutiedot'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaksutietohuoltajuussuhde',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical maksutieto huoltajuussuhde', 'verbose_name_plural': 'historical maksutiedot huoltajuussuhteet'},
        ),
        migrations.AlterModelOptions(
            name='historicalorganisaatio',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organisaatio', 'verbose_name_plural': 'historical organisaatiot'},
        ),
        migrations.AlterModelOptions(
            name='historicalpalvelussuhde',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical palvelussuhde', 'verbose_name_plural': 'historical palvelussuhteet'},
        ),
        migrations.AlterModelOptions(
            name='historicalpaosoikeus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical paos oikeus', 'verbose_name_plural': 'historical Paos-oikeudet'},
        ),
        migrations.AlterModelOptions(
            name='historicalpaostoiminta',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical paos toiminta', 'verbose_name_plural': 'historical Paos-toiminnat'},
        ),
        migrations.AlterModelOptions(
            name='historicalpidempipoissaolo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pidempi poissaolo', 'verbose_name_plural': 'historical pidemmatpoissaolot'},
        ),
        migrations.AlterModelOptions(
            name='historicaltaydennyskoulutus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical taydennyskoulutus', 'verbose_name_plural': 'historical taydennyskoulutukset'},
        ),
        migrations.AlterModelOptions(
            name='historicaltaydennyskoulutustyontekija',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical taydennyskoulutus tyontekija', 'verbose_name_plural': 'historical taydennyskoulutukset tyontekijat'},
        ),
        migrations.AlterModelOptions(
            name='historicaltilapainenhenkilosto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tilapainen henkilosto', 'verbose_name_plural': 'historical tilapainen henkilosto'},
        ),
        migrations.AlterModelOptions(
            name='historicaltoiminnallinenpainotus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical toiminnallinen painotus', 'verbose_name_plural': 'historical toiminnalliset painotukset'},
        ),
        migrations.AlterModelOptions(
            name='historicaltoimipaikka',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical toimipaikka', 'verbose_name_plural': 'historical toimipaikat'},
        ),
        migrations.AlterModelOptions(
            name='historicaltutkinto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tutkinto', 'verbose_name_plural': 'historical tutkinnot'},
        ),
        migrations.AlterModelOptions(
            name='historicaltyontekija',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tyontekija', 'verbose_name_plural': 'historical tyontekijat'},
        ),
        migrations.AlterModelOptions(
            name='historicaltyoskentelypaikka',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tyoskentelypaikka', 'verbose_name_plural': 'historical tyoskentelypaikat'},
        ),
        migrations.AlterModelOptions(
            name='historicalvarhaiskasvatuspaatos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical varhaiskasvatuspaatos', 'verbose_name_plural': 'historical varhaiskasvatuspaatokset'},
        ),
        migrations.AlterModelOptions(
            name='historicalvarhaiskasvatussuhde',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical varhaiskasvatussuhde', 'verbose_name_plural': 'historical varhaiskasvatussuhteet'},
        ),
        migrations.AlterModelOptions(
            name='historicalyearlyreportsummary',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical yearly report summary', 'verbose_name_plural': 'historical yearlyreportsummaries'},
        ),
        migrations.AlterField(
            model_name='historicalhenkilo',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalhuoltaja',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalhuoltajuussuhde',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalkielipainotus',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallapsi',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaksutieto',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaksutietohuoltajuussuhde',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalorganisaatio',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpalvelussuhde',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpaosoikeus',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpaostoiminta',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpidempipoissaolo',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltaydennyskoulutus',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltaydennyskoulutustyontekija',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltilapainenhenkilosto',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltoiminnallinenpainotus',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltoimipaikka',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltutkinto',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltyontekija',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltyoskentelypaikka',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvarhaiskasvatuspaatos',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvarhaiskasvatussuhde',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalyearlyreportsummary',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
