# Generated by Django 4.0.7 on 2022-10-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0072_historicalyearlyreportsummary_toimipaikka_by_toimintamuoto_count_and_more'),
    ]

    operations = [
        # Create indexes for historical-tables. Cannot create them via Django so do it manually.
        migrations.RunSQL(
            '''
            CREATE INDEX varda_historicalorganisaatio_id_hist_sb5od8_idx ON varda_historicalorganisaatio USING btree (id, history_date DESC);
            CREATE INDEX varda_historicaltoimipaikka_id_hist_d354up_idx ON varda_historicaltoimipaikka USING btree (id, history_date DESC);
            CREATE INDEX varda_historicalkielipainotus_id_hist_469p97_idx ON varda_historicalkielipainotus USING btree (id, history_date DESC);
            CREATE INDEX varda_historicaltoiminnallinenpainotus_id_hist_011ue0_idx ON varda_historicaltoiminnallinenpainotus USING btree (id, history_date DESC);
            CREATE INDEX varda_historicalhenkilo_id_hist_q647it_idx ON varda_historicalhenkilo USING btree (id, history_date DESC);
            CREATE INDEX varda_historicallapsi_id_hist_hcmv2h_idx ON varda_historicallapsi USING btree (id, history_date DESC);
            CREATE INDEX varda_historicalvarhaiskasvatuspaatos_id_hist_0v2j93_idx ON varda_historicalvarhaiskasvatuspaatos USING btree (id, history_date DESC);
            CREATE INDEX varda_historicalvarhaiskasvatussuhde_id_hist_6a4zj6_idx ON varda_historicalvarhaiskasvatussuhde USING btree (id, history_date DESC);
            CREATE INDEX varda_historicalmaksutieto_id_hist_dowh59_idx ON varda_historicalmaksutieto USING btree (id, history_date DESC);
            CREATE INDEX varda_historicalmaksutietohuoltajuussuhde_maks_hist_8k5bvy_idx ON varda_historicalmaksutietohuoltajuussuhde USING btree (maksutieto_id, history_date DESC);
            CREATE INDEX varda_historicalmaksutietohuoltajuussuhde_huol_hist_x6560w_idx ON varda_historicalmaksutietohuoltajuussuhde USING btree (huoltajuussuhde_id, history_date DESC);
            CREATE INDEX varda_historicalhuoltajuussuhde_id_hist_uj5grc_idx ON varda_historicalhuoltajuussuhde USING btree (id, history_date DESC);
            CREATE INDEX varda_historicaltyontekija_id_hist_0jt1uo_idx ON varda_historicaltyontekija USING btree (id, history_date DESC);
            CREATE INDEX varda_historicalpalvelussuhde_id_hist_zo8nx6_idx ON varda_historicalpalvelussuhde USING btree (id, history_date DESC);
            CREATE INDEX varda_historicaltyoskentelypaikka_id_hist_i45319_idx ON varda_historicaltyoskentelypaikka USING btree (id, history_date DESC);
            CREATE INDEX varda_historicalpidempipoissaolo_id_hist_ar7xdu_idx ON varda_historicalpidempipoissaolo USING btree (id, history_date DESC);
            CREATE INDEX varda_historicaltaydennyskoulutus_id_hist_ab98mr_idx ON varda_historicaltaydennyskoulutus USING btree (id, history_date DESC);
            CREATE INDEX varda_historicaltaydennyskoulutustyontekija_tayd_hist_279jz0_idx ON varda_historicaltaydennyskoulutustyontekija USING btree (taydennyskoulutus_id, history_date DESC);
            CREATE INDEX varda_historicaltaydennyskoulutustyontekija_tyon_hist_7380r3_idx ON varda_historicaltaydennyskoulutustyontekija USING btree (tyontekija_id, history_date DESC);
            ''',
            reverse_sql='''
            DROP INDEX varda_historicalorganisaatio_id_hist_sb5od8_idx;
            DROP INDEX varda_historicaltoimipaikka_id_hist_d354up_idx;
            DROP INDEX varda_historicalkielipainotus_id_hist_469p97_idx;
            DROP INDEX varda_historicaltoiminnallinenpainotus_id_hist_011ue0_idx;
            DROP INDEX varda_historicalhenkilo_id_hist_q647it_idx;
            DROP INDEX varda_historicallapsi_id_hist_hcmv2h_idx;
            DROP INDEX varda_historicalvarhaiskasvatuspaatos_id_hist_0v2j93_idx;
            DROP INDEX varda_historicalvarhaiskasvatussuhde_id_hist_6a4zj6_idx;
            DROP INDEX varda_historicalmaksutieto_id_hist_dowh59_idx;
            DROP INDEX varda_historicalmaksutietohuoltajuussuhde_maks_hist_8k5bvy_idx;
            DROP INDEX varda_historicalmaksutietohuoltajuussuhde_huol_hist_x6560w_idx;
            DROP INDEX varda_historicalhuoltajuussuhde_id_hist_uj5grc_idx;
            DROP INDEX varda_historicaltyontekija_id_hist_0jt1uo_idx;
            DROP INDEX varda_historicalpalvelussuhde_id_hist_zo8nx6_idx;
            DROP INDEX varda_historicaltyoskentelypaikka_id_hist_i45319_idx;
            DROP INDEX varda_historicalpidempipoissaolo_id_hist_ar7xdu_idx;
            DROP INDEX varda_historicaltaydennyskoulutus_id_hist_ab98mr_idx;
            DROP INDEX varda_historicaltaydennyskoulutustyontekija_tayd_hist_279jz0_idx;
            DROP INDEX varda_historicaltaydennyskoulutustyontekija_tyon_hist_7380r3_idx;
            '''
        ),
        migrations.RunSQL(
            'UPDATE varda_z8_excelreport SET target_date = target_date_start WHERE target_date_start IS NOT NULL;',
            reverse_sql='UPDATE varda_z8_excelreport SET target_date_start = target_date, target_date = NULL WHERE target_date_end IS NOT NULL;'
        ),
        migrations.RunSQL(
            'UPDATE varda_z8_excelreportlog SET target_date = target_date_start WHERE target_date_start IS NOT NULL;',
            reverse_sql='UPDATE varda_z8_excelreportlog SET target_date_start = target_date, target_date = NULL WHERE target_date_end IS NOT NULL;'
        ),
        migrations.AlterField(
            model_name='z8_excelreportlog',
            name='toimipaikka',
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField(
            model_name='z8_excelreportlog',
            old_name='toimipaikka',
            new_name='toimipaikka_id'
        ),
        migrations.AlterField(
            model_name='z8_excelreport',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RenameField(
            model_name='z8_excelreport',
            old_name='vakajarjestaja',
            new_name='organisaatio',
        ),
        migrations.RenameField(
            model_name='z8_excelreport',
            old_name='target_date_end',
            new_name='target_date_secondary',
        ),
        migrations.RenameField(
            model_name='z8_excelreportlog',
            old_name='vakajarjestaja',
            new_name='organisaatio',
        ),
        migrations.RenameField(
            model_name='z8_excelreportlog',
            old_name='target_date_end',
            new_name='target_date_secondary',
        ),
        migrations.AlterField(
            model_name='z8_excelreport',
            name='organisaatio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excel_reports', to='varda.organisaatio'),
        ),
        migrations.AlterField(
            model_name='z8_excelreportlog',
            name='organisaatio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excel_report_logs', to='varda.organisaatio'),
        ),
        migrations.RemoveField(
            model_name='z8_excelreport',
            name='target_date_start',
        ),
        migrations.RemoveField(
            model_name='z8_excelreportlog',
            name='target_date_start',
        ),
        migrations.AddField(
            model_name='z8_excelreport',
            name='report_subtype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='z8_excelreportlog',
            name='report_subtype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='yearlyreportsummary',
            name='vakajarjestaja',
        ),
        migrations.DeleteModel(
            name='HistoricalYearlyReportSummary',
        ),
        migrations.DeleteModel(
            name='YearlyReportSummary',
        )
    ]
