# Generated by Django 4.2 on 2023-05-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0079_z3_additionalcasuserfields_all_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='z2_codetranslation',
            name='short_name',
        ),
    ]
