# Generated by Django 4.2 on 2023-06-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0081_z11_messagelog_z11_messagetarget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltoimipaikka',
            old_name='asiointikieli_koodi',
            new_name='toimintakieli_koodi',
        ),
        migrations.RenameField(
            model_name='toimipaikka',
            old_name='asiointikieli_koodi',
            new_name='toimintakieli_koodi',
        ),
    ]
