# Generated by Django 4.2.10 on 2024-03-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0086_tukipaatosaikavali_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='z3_additionalcasuserfields',
            old_name='asiointikieli_koodi',
            new_name='toimintakieli_koodi',
        ),
    ]
