# Generated by Django 4.2.9 on 2024-03-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0087_rename_asiointikieli_koodi_z3_additionalcasuserfields_toimintakieli_koodi'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lapsi',
            constraint=models.UniqueConstraint(condition=models.Q(('vakatoimija__isnull', False)), fields=('henkilo', 'vakatoimija'), name='lapsi_vakatoimija_unique_constraint'),
        ),
    ]
