# Generated by Django 5.0.6 on 2024-08-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0089_historicalorganisaatio_client_cert_common_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltukipaatos',
            old_name='lapsimaara',
            new_name='paatosmaara',
        ),
        migrations.RenameField(
            model_name='tukipaatos',
            old_name='lapsimaara',
            new_name='paatosmaara',
        ),
    ]
