# Generated by Django 5.0.9 on 2024-11-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0091_add_update_user_limitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReports',
            fields=[
                ('organisaatio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='error_reports', serialize=False, to='varda.organisaatio')),
                ('active_errors', models.BooleanField(default=False)),
                ('muutos_pvm', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Error reports',
            },
        ),
    ]
