# Generated by Django 5.1.3 on 2025-02-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("varda", "0093_alter_historicaltoimipaikka_kayntiosoite_postinumero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="z8_excelreport",
            name="admin_user_all_organizations",
            field=models.BooleanField(default=False),
        ),
    ]
