# Generated by Django 5.2.6 on 2025-10-09 08:39

import varda.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("varda", "0094_z8_excelreport_admin_user_all_organizations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltoimipaikka",
            name="postinumero",
            field=models.CharField(
                max_length=20, validators=[varda.validators.validate_postinumero]
            ),
        ),
        migrations.AlterField(
            model_name="toimipaikka",
            name="postinumero",
            field=models.CharField(
                max_length=20, validators=[varda.validators.validate_postinumero]
            ),
        ),
    ]
