# Generated by Django 2.2.10 on 2020-03-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0014_auto_20191127_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaydennyskoulutus',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltaydennyskoulutus',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltaydennyskoulutus',
            name='tyontekija',
        ),
        migrations.RemoveField(
            model_name='historicaltyontekija',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltyontekija',
            name='henkilo',
        ),
        migrations.RemoveField(
            model_name='historicaltyontekija',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='ohjaajasuhde',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='ohjaajasuhde',
            name='toimipaikka',
        ),
        migrations.RemoveField(
            model_name='ohjaajasuhde',
            name='tyontekija',
        ),
        migrations.RemoveField(
            model_name='taydennyskoulutus',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='taydennyskoulutus',
            name='tyontekija',
        ),
        migrations.RemoveField(
            model_name='tyontekija',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='tyontekija',
            name='henkilo',
        ),
        migrations.AddField(
            model_name='historicalpaostoiminta',
            name='voimassa_kytkin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paostoiminta',
            name='voimassa_kytkin',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='HistoricalOhjaajasuhde',
        ),
        migrations.DeleteModel(
            name='HistoricalTaydennyskoulutus',
        ),
        migrations.DeleteModel(
            name='HistoricalTyontekija',
        ),
        migrations.DeleteModel(
            name='Ohjaajasuhde',
        ),
        migrations.DeleteModel(
            name='Taydennyskoulutus',
        ),
        migrations.DeleteModel(
            name='Tyontekija',
        ),
    ]
