# Generated by Django 2.2.9 on 2019-12-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0014_auto_20191127_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaostoiminta',
            name='voimassa_kytkin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paostoiminta',
            name='voimassa_kytkin',
            field=models.BooleanField(default=True),
        ),
    ]
