# Generated by Django 2.2.11 on 2020-05-12 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import varda.models
import varda.validators


def forwards_func(apps, schema_editor):
    Z2_Koodisto = apps.get_model('varda', 'Z2_Koodisto')
    db_alias = schema_editor.connection.alias
    Z2_Koodisto.objects.using(db_alias).update(tutkinto_koodit=varda.models.tutkinto_koodit_default())


def reverse_func(apps, schema_editor):
    Z2_Koodisto = apps.get_model('varda', 'Z2_Koodisto')
    db_alias = schema_editor.connection.alias
    Z2_Koodisto.objects.using(db_alias).update(tutkinto_koodit=['003'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varda', '0020_auto_20200428_0945'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.CreateModel(
            name='Tutkinto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutkinto_koodi', models.CharField(max_length=10, validators=[varda.validators.validate_tutkinto_koodi])),
                ('luonti_pvm', models.DateTimeField(auto_now_add=True)),
                ('muutos_pvm', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutkinnot', to=settings.AUTH_USER_MODEL)),
                ('henkilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutkinnot', to='varda.Henkilo')),
            ],
            options={
                'verbose_name_plural': 'tutkinnot',
            },
        ),
        migrations.CreateModel(
            name='TilapainenHenkilosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuukausi', models.DateField()),
                ('tuntimaara', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tyontekijamaara', models.IntegerField()),
                ('lahdejarjestelma', models.CharField(max_length=2, validators=[varda.validators.validate_lahdejarjestelma_koodi])),
                ('tunniste', models.CharField(blank=True, max_length=120, null=True, validators=[varda.validators.validate_tunniste])),
                ('luonti_pvm', models.DateTimeField(auto_now_add=True)),
                ('muutos_pvm', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tilapainen_henkilosto', to=settings.AUTH_USER_MODEL)),
                ('vakajarjestaja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tilapainen_henkilosto', to='varda.VakaJarjestaja')),
            ],
            options={
                'verbose_name_plural': 'tilapainen henkilosto',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTutkinto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tutkinto_koodi', models.CharField(max_length=10, validators=[varda.validators.validate_tutkinto_koodi])),
                ('luonti_pvm', models.DateTimeField(blank=True, editable=False)),
                ('muutos_pvm', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('henkilo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.Henkilo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tutkinto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTilapainenHenkilosto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kuukausi', models.DateField()),
                ('tuntimaara', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tyontekijamaara', models.IntegerField()),
                ('lahdejarjestelma', models.CharField(max_length=2, validators=[varda.validators.validate_lahdejarjestelma_koodi])),
                ('tunniste', models.CharField(blank=True, max_length=120, null=True, validators=[varda.validators.validate_tunniste])),
                ('luonti_pvm', models.DateTimeField(blank=True, editable=False)),
                ('muutos_pvm', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vakajarjestaja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.VakaJarjestaja')),
            ],
            options={
                'verbose_name': 'historical tilapainen henkilosto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
