# Generated by Django 2.2.10 on 2020-05-19 06:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varda', '0021_auto_20200512_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palvelussuhde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyosuhde_koodi', models.CharField(max_length=50, validators=[varda.validators.validate_tyosuhde_koodi])),
                ('tyoaika_koodi', models.CharField(max_length=50, validators=[varda.validators.validate_tyoaika_koodi])),
                ('tutkinto_koodi', models.CharField(max_length=50, validators=[varda.validators.validate_tutkinto_koodi])),
                ('tyoaika_viikossa', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('alkamis_pvm', models.DateField()),
                ('paattymis_pvm', models.DateField(blank=True, default=None, null=True)),
                ('lahdejarjestelma', models.CharField(max_length=2, validators=[varda.validators.validate_lahdejarjestelma_koodi])),
                ('tunniste', models.CharField(blank=True, max_length=120, null=True, validators=[varda.validators.validate_tunniste])),
                ('luonti_pvm', models.DateTimeField(auto_now_add=True)),
                ('muutos_pvm', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palvelussuhteet', to=settings.AUTH_USER_MODEL)),
                ('tyontekija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palvelussuhteet', to='varda.Tyontekija')),
            ],
            options={
                'verbose_name_plural': 'palvelussuhteet',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPalvelussuhde',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tyosuhde_koodi', models.CharField(max_length=50, validators=[varda.validators.validate_tyosuhde_koodi])),
                ('tyoaika_koodi', models.CharField(max_length=50, validators=[varda.validators.validate_tyoaika_koodi])),
                ('tutkinto_koodi', models.CharField(max_length=50, validators=[varda.validators.validate_tutkinto_koodi])),
                ('tyoaika_viikossa', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('alkamis_pvm', models.DateField()),
                ('paattymis_pvm', models.DateField(blank=True, default=None, null=True)),
                ('lahdejarjestelma', models.CharField(max_length=2, validators=[varda.validators.validate_lahdejarjestelma_koodi])),
                ('tunniste', models.CharField(blank=True, max_length=120, null=True, validators=[varda.validators.validate_tunniste])),
                ('luonti_pvm', models.DateTimeField(blank=True, editable=False)),
                ('muutos_pvm', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tyontekija', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='varda.Tyontekija')),
            ],
            options={
                'verbose_name': 'historical palvelussuhde',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
