# Generated by Django 2.2.11 on 2020-06-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0022_auto_20200604_1002'),
    ]

    operations = [
    ]
