# Generated by Django 2.2.11 on 2020-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0025_auto_20200623_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batcherror',
            name='type',
            field=models.TextField(choices=[('LAPSI_HUOLTAJUUSSUHDE_UPDATE', 'LAPSI_HUOLTAJUUSSUHDE_UPDATE'), ('HENKILOTIETO_UPDATE', 'HENKILOTIETO_UPDATE')]),
        ),
    ]
