# Generated by Django 2.2.13 on 2020-08-10 08:52

import django.core.validators
from django.db import migrations, models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0028_auto_20200803_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpalvelussuhde',
            name='paattymis_pvm',
            field=models.DateField(blank=True, default=None, null=True, validators=[varda.validators.validate_palvelussuhde_paattymis_pvm]),
        ),
        migrations.AlterField(
            model_name='historicalpalvelussuhde',
            name='tyoaika_viikossa',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='palvelussuhde',
            name='paattymis_pvm',
            field=models.DateField(blank=True, default=None, null=True, validators=[varda.validators.validate_palvelussuhde_paattymis_pvm]),
        ),
        migrations.AlterField(
            model_name='palvelussuhde',
            name='tyoaika_viikossa',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
    ]
