# Generated by Django 3.1.4 on 2021-04-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0046_auto_20210319_0957'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='henkilo',
            name='henkilo_oid_henkilotunnus_unique_hash_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='henkilo',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, henkilotunnus_unique_hash=''), fields=('henkilotunnus_unique_hash',), name='henkilo_henkilotunnus_unique_hash_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='henkilo',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, henkilo_oid=''), fields=('henkilo_oid',), name='henkilo_oid_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='kielipainotus',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='kielipainotus_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='lapsi',
            constraint=models.UniqueConstraint(condition=models.Q(vakatoimija__isnull=False), fields=('henkilo', 'vakatoimija'), name='lapsi_vakatoimija_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='lapsi',
            constraint=models.UniqueConstraint(condition=models.Q(('oma_organisaatio__isnull', False), ('paos_organisaatio__isnull', False)), fields=('henkilo', 'oma_organisaatio', 'paos_organisaatio'), name='lapsi_paos_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='lapsi',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='lapsi_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='maksutieto',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='maksutieto_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='palvelussuhde',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='palvelussuhde_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='pidempipoissaolo',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='pidempi_poissaolo_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='taydennyskoulutus',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='taydennyskoulutus_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='tilapainenhenkilosto',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='tilapainen_henkilosto_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='toiminnallinenpainotus',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='toiminnallinen_painotus_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='toimipaikka',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='toimipaikka_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='tyontekija',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='tyontekija_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='tyoskentelypaikka',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='tyoskentelypaikka_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='varhaiskasvatuspaatos',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='vakapaatos_lahdejarjestelma_tunniste_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='varhaiskasvatussuhde',
            constraint=models.UniqueConstraint(condition=models.Q(('tunniste__isnull', False), models.Q(_negated=True, tunniste='')), fields=('lahdejarjestelma', 'tunniste'), name='vakasuhde_lahdejarjestelma_tunniste_unique_constraint'),
        ),
    ]
