# Generated by Django 3.1.4 on 2021-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0049_auto_20210526_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='z8_excelreportlog',
            name='encryption_duration',
            field=models.IntegerField(default=0),
        ),
    ]
