# Generated by Django 3.2.7 on 2021-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0054_maksutieto_huoltajuussuhde'),
    ]

    operations = [
        migrations.AddField(
            model_name='z8_excelreportlog',
            name='report_id',
            field=models.IntegerField(null=True),
        ),
    ]
