# Generated by Django 4.0.5 on 2022-07-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0070_z10_kelavarhaiskasvatussuhde_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='z10_kelavarhaiskasvatussuhde',
            index=models.Index(fields=['henkilo_id', 'suhde_alkamis_pvm', 'suhde_paattymis_pvm'], name='varda_z10_k_henkilo_5c6cba_idx'),
        ),
    ]
