export enum VardaKayttooikeusRoles {
  VARDA_PAAKAYTTAJA = 'VARDA-PAAKAYTTAJA',
  VARDA_TALLENTAJA = 'VARDA-TALLENTAJA',
  VARDA_KATSELIJA = 'VARDA-KATSELIJA',
  VARDA_HUOLTAJA_TALLENTAJA = 'HUOLTAJATIETO_TALLENNUS',
  VARDA_HUOLTAJA_KATSELIJA = 'HUOLTAJATIETO_KATSELU',
  HENKILOSTO_TYONTEKIJA_TALLENTAJA = 'HENKILOSTO_TYONTEKIJA_TALLENTAJA',
  HENKILOSTO_TAYDENNYSKOULUTUS_TALLENTAJA = 'HENKILOSTO_TAYDENNYSKOULUTUS_TALLENTAJA',
  HENKILOSTO_VUOKRATTU_TALLENTAJA = 'HENKILOSTO_VUOKRATTU_TALLENTAJA',
  HENKILOSTO_TYONTEKIJA_KATSELIJA = 'HENKILOSTO_TYONTEKIJA_KATSELIJA',
  TUEN_TIEDOT_TALLENTAJA = 'TUEN_TIEDOT_TALLENTAJA',
  TUEN_TIEDOT_KATSELIJA = 'TUEN_TIEDOT_KATSELIJA',
  HENKILOSTO_TAYDENNYSKOULUTUS_KATSELIJA = 'HENKILOSTO_TAYDENNYSKOULUTUS_KATSELIJA',
  HENKILOSTO_VUOKRATTU_KATSELIJA = 'HENKILOSTO_VUOKRATTU_KATSELIJA',
  TOIMIJATIEDOT_KATSELIJA = 'VARDA_TOIMIJATIEDOT_KATSELIJA',
  TOIMIJATIEDOT_TALLENTAJA = 'VARDA_TOIMIJATIEDOT_TALLENTAJA',
  RAPORTTIEN_KATSELIJA = 'VARDA_RAPORTTIEN_KATSELIJA'
}
