export enum VardaKayttajatyyppi {
  ADMIN = 'ADMIN',
  PALVELU = 'PALVELU',
  VIRKAILIJA = 'VIRKAILIJA',
  OPH_STAFF = 'OPH_STAFF',
  OPPIJA_CAS = 'OPPIJA_CAS',
  OPPIJA_CAS_VALTUUDET = 'OPPIJA_CAS_VALTUUDET'
}
