export enum VardaKayttooikeusRoles {
  VARDA_PAAKAYTTAJA = 'VARDA-PAAKAYTTAJA',
  VARDA_TALLENTAJA = 'VARDA-TALLENTAJA',
  VARDA_KATSELIJA = 'VARDA-KATSELIJA',
  VARDA_HUOLTAJA_TALLENTAJA = 'HUOLTAJATIETO_TALLENNUS',
  VARDA_HUOLTAJA_KATSELIJA = 'HUOLTAJATIETO_KATSELU',
}
