export enum VardaKayttooikeusRoles {
  VARDA_PAAKAYTTAJA = 'VARDA-PAAKAYTTAJA',
  VARDA_TALLENTAJA = 'VARDA-TALLENTAJA',
  VARDA_KATSELIJA = 'VARDA-KATSELIJA',
  VARDA_HUOLTAJA_TALLENTAJA = 'HUOLTAJATIETO_TALLENNUS',
  VARDA_HUOLTAJA_KATSELIJA = 'HUOLTAJATIETO_KATSELU',
  HENKILOSTO_TYONTEKIJA_TALLENTAJA = 'HENKILOSTO_TYONTEKIJA_TALLENTAJA',
  HENKILOSTO_TAYDENNYSKOULUTUS_TALLENTAJA = 'HENKILOSTO_TAYDENNYSKOULUTUS_TALLENTAJA',
  HENKILOSTO_TILAPAISET_TALLENTAJA = 'HENKILOSTO_TILAPAISET_TALLENTAJA',
  HENKILOSTO_TYONTEKIJA_KATSELIJA = 'HENKILOSTO_TYONTEKIJA_KATSELIJA',
  HENKILOSTO_TAYDENNYSKOULUTUS_KATSELIJA = 'HENKILOSTO_TAYDENNYSKOULUTUS_KATSELIJA',
  HENKILOSTO_TILAPAISET_KATSELIJA = 'HENKILOSTO_TILAPAISET_KATSELIJA'
}
